# Generated by Django 4.0.1 on 2022-01-12 02:23

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog_title', models.CharField(max_length=255)),
                ('blog_image', models.ImageField(upload_to=mainapp.models.upload_image_path)),
                ('blog_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
